In [66]:
import sys
sys.path.insert(0, '.././')  # add grandparent directory to sys.path

In [67]:
from src.mediapipe import GooMedia
import cv2
import numpy as np
from src.visualize import *
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from src.utils import image_resize
from src.geometry import get_points_media
from src.geometry import distance_entre_points
from PIL import Image

In [68]:
%matplotlib qt

In [69]:
pairs_l = [(0, 4), (1, 3), (2, 5)]

In [70]:
def distance_mean(eyelid_list, pairs):
    dist1 = distance_entre_points(eyelid_list, pairs[0][0], pairs[0][1])
    dist2 = distance_entre_points(eyelid_list, pairs[1][0], pairs[1][1])
    dist3 = distance_entre_points(eyelid_list, pairs[2][0], pairs[2][1])
    return np.mean([dist1, dist2, dist3])

In [71]:
def eyelid_comparsion(eyelid_bottom, eyelid_mid, eyelid_top, pairs):
    if distance_mean(eyelid_top, pairs) < distance_mean(eyelid_bottom, pairs):
        return "Os olhos se abaixaram, comportamento esperado"
    else:
        return "Os olhos se levantaram, comportamento anormal"

In [72]:
pface = GooMedia(1080) # Extrator dos pontos

In [73]:
image_cima = cv2.imread(r"..\images\inputs\9pointscamera\9points_x50_y17.jpg")
image_medio = cv2.imread(r"..\images\inputs\9pointscamera\9points_x50_y50.jpg")
image_baixo = cv2.imread(r"..\images\inputs\9pointscamera\9points_x50_y83.jpg")

In [74]:
image_resize_top , landmask_cima = pface.extract(image_cima)
image_resize_mid , landmask_medio = pface.extract(image_medio)
image_resize_bottom , landmask_baixo = pface.extract(image_baixo)

In [75]:
points_top = pface.points_normalize(landmask_cima, image_cima.shape, index=0)
points_mid = pface.points_normalize(landmask_medio, image_medio.shape, index=0)
points_bottom = pface.points_normalize(landmask_baixo, image_baixo.shape, index=0)


In [76]:
eyelid_l_top = get_points_media(points_top, 'eyelid_l')
eyelid_l_mid = get_points_media(points_mid, 'eyelid_l')
eyelid_l_bottom = get_points_media(points_bottom, 'eyelid_l')

In [77]:
points_eyelid_top = draw_face_one_color(image_resize_top, eyelid_l_top)
points_eyelid_mid = draw_face_one_color(image_resize_mid, eyelid_l_mid)
points_eyelid_bottom = draw_face_one_color(image_resize_bottom, eyelid_l_bottom)

In [78]:
plt.figure()
cv2.line(image_resize_top, eyelid_l_top[2], eyelid_l_top[5], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_top, eyelid_l_top[0], eyelid_l_top[4], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_top, eyelid_l_top[1], eyelid_l_top[3], color=(255, 0, 0), thickness=1)
plt.imshow(points_eyelid_top[...,::-1])

In [79]:
plt.figure()
cv2.line(image_resize_mid, eyelid_l_mid[2], eyelid_l_mid[5], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_mid, eyelid_l_mid[0], eyelid_l_mid[4], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_mid, eyelid_l_mid[1], eyelid_l_mid[3], color=(255, 0, 0), thickness=1)
plt.imshow(points_eyelid_mid[...,::-1])

In [80]:
plt.figure()
cv2.line(image_resize_bottom, eyelid_l_bottom[2], eyelid_l_bottom[5], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_bottom, eyelid_l_bottom[0], eyelid_l_bottom[4], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_bottom, eyelid_l_bottom[1], eyelid_l_bottom[3], color=(255, 0, 0), thickness=1)
plt.imshow(points_eyelid_bottom[...,::-1]) 
plt.show()
# open new window

In [81]:
eyelid_l_bottom[0]

array([203, 267])

In [82]:
print(distance_entre_points(eyelid_l_bottom, 2, 5))

10.816653826391969


In [83]:
print(distance_entre_points(eyelid_l_mid, 2, 5))

11.40175425099138


In [84]:
print(distance_entre_points(eyelid_l_top, 2, 5))

10.0


In [85]:
print(distance_entre_points(eyelid_l_bottom, 0, 4))

10.770329614269007


In [86]:
print(distance_entre_points(eyelid_l_mid, 0, 4))

10.295630140987


In [87]:
print(distance_entre_points(eyelid_l_top, 0, 4))

8.94427190999916


In [88]:
print(distance_entre_points(eyelid_l_bottom, 1, 3))

9.055385138137417


In [89]:
print(distance_entre_points(eyelid_l_mid, 1, 3))

9.219544457292887


In [90]:
print(distance_entre_points(eyelid_l_top, 1, 3))

8.246211251235321


In [91]:
print(eyelid_comparsion(eyelid_l_bottom, eyelid_l_mid, eyelid_l_top, pairs_l))

Os olhos se abaixaram, comportamento esperado


--------------------------------------

In [92]:
image_cima = cv2.imread(r"..\images\inputs\artur\9pointscamera\9points_x50_y17.jpg")
image_medio = cv2.imread(r"..\images\inputs\artur\9pointscamera\9points_x50_y50.jpg")
image_baixo = cv2.imread(r"..\images\inputs\artur\9pointscamera\9points_x50_y83.jpg")

In [93]:
image_resize_top , landmask_cima = pface.extract(image_cima)
image_resize_mid , landmask_medio = pface.extract(image_medio)
image_resize_bottom , landmask_baixo = pface.extract(image_baixo)

In [94]:
points_top = pface.points_normalize(landmask_cima, image_cima.shape, index=0)
points_mid = pface.points_normalize(landmask_medio, image_medio.shape, index=0)
points_bottom = pface.points_normalize(landmask_baixo, image_baixo.shape, index=0)


In [95]:
eyelid_l_top = get_points_media(points_top, 'eyelid_l')
eyelid_l_mid = get_points_media(points_mid, 'eyelid_l')
eyelid_l_bottom = get_points_media(points_bottom, 'eyelid_l')

In [96]:
points_eyelid_top = draw_face_one_color(image_resize_top, eyelid_l_top)
points_eyelid_mid = draw_face_one_color(image_resize_mid, eyelid_l_mid)
points_eyelid_bottom = draw_face_one_color(image_resize_bottom, eyelid_l_bottom)

In [97]:
plt.figure()
cv2.line(image_resize_top, eyelid_l_top[2], eyelid_l_top[5], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_top, eyelid_l_top[0], eyelid_l_top[4], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_top, eyelid_l_top[1], eyelid_l_top[3], color=(255, 0, 0), thickness=1)
plt.imshow(points_eyelid_top[...,::-1])

In [98]:
plt.figure()
cv2.line(image_resize_mid, eyelid_l_mid[2], eyelid_l_mid[5], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_mid, eyelid_l_mid[0], eyelid_l_mid[4], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_mid, eyelid_l_mid[1], eyelid_l_mid[3], color=(255, 0, 0), thickness=1)
plt.imshow(points_eyelid_mid[...,::-1])

In [99]:
plt.figure()
cv2.line(image_resize_bottom, eyelid_l_bottom[2], eyelid_l_bottom[5], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_bottom, eyelid_l_bottom[0], eyelid_l_bottom[4], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_bottom, eyelid_l_bottom[1], eyelid_l_bottom[3], color=(255, 0, 0), thickness=1)
plt.imshow(points_eyelid_bottom[...,::-1]) 
plt.show()
# open new window

In [100]:
eyelid_l_bottom[0]

array([180, 289])

In [101]:
print(distance_entre_points(eyelid_l_bottom, 2, 5))

10.295630140987


In [102]:
print(distance_entre_points(eyelid_l_mid, 2, 5))

9.433981132056603


In [103]:
print(distance_entre_points(eyelid_l_top, 2, 5))

8.94427190999916


In [104]:
print(distance_entre_points(eyelid_l_bottom, 0, 4))

9.486832980505138


In [105]:
print(distance_entre_points(eyelid_l_mid, 0, 4))

8.54400374531753


In [106]:
print(distance_entre_points(eyelid_l_top, 0, 4))

8.54400374531753


In [107]:
print(distance_entre_points(eyelid_l_bottom, 1, 3))

8.06225774829855


In [108]:
print(distance_entre_points(eyelid_l_mid, 1, 3))

7.0


In [109]:
print(distance_entre_points(eyelid_l_top, 1, 3))

7.0


In [110]:
print(eyelid_comparsion(eyelid_l_bottom, eyelid_l_mid, eyelid_l_top, pairs_l))

Os olhos se abaixaram, comportamento esperado


-------------------------------

In [111]:
image_cima = cv2.imread(r"..\images\inputs\artur\9pointscamera\distant\9points_x50_y17.jpg")
image_medio = cv2.imread(r"..\images\inputs\artur\9pointscamera\distant\9points_x50_y50.jpg")
image_baixo = cv2.imread(r"..\images\inputs\artur\9pointscamera\distant\9points_x50_y83.jpg")

In [112]:
image_resize_top , landmask_cima = pface.extract(image_cima)
image_resize_mid , landmask_medio = pface.extract(image_medio)
image_resize_bottom , landmask_baixo = pface.extract(image_baixo)

In [113]:
points_top = pface.points_normalize(landmask_cima, image_cima.shape, index=0)
points_mid = pface.points_normalize(landmask_medio, image_medio.shape, index=0)
points_bottom = pface.points_normalize(landmask_baixo, image_baixo.shape, index=0)


In [114]:
eyelid_l_top = get_points_media(points_top, 'eyelid_l')
eyelid_l_mid = get_points_media(points_mid, 'eyelid_l')
eyelid_l_bottom = get_points_media(points_bottom, 'eyelid_l')

In [115]:
points_eyelid_top = draw_face_one_color(image_resize_top, eyelid_l_top)
points_eyelid_mid = draw_face_one_color(image_resize_mid, eyelid_l_mid)
points_eyelid_bottom = draw_face_one_color(image_resize_bottom, eyelid_l_bottom)

In [116]:
plt.figure()
cv2.line(image_resize_top, eyelid_l_top[2], eyelid_l_top[5], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_top, eyelid_l_top[0], eyelid_l_top[4], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_top, eyelid_l_top[1], eyelid_l_top[3], color=(255, 0, 0), thickness=1)
plt.imshow(points_eyelid_top[...,::-1])

In [117]:
plt.figure()
cv2.line(image_resize_mid, eyelid_l_mid[2], eyelid_l_mid[5], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_mid, eyelid_l_mid[0], eyelid_l_mid[4], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_mid, eyelid_l_mid[1], eyelid_l_mid[3], color=(255, 0, 0), thickness=1)
plt.imshow(points_eyelid_mid[...,::-1])

In [118]:
plt.figure()
cv2.line(image_resize_bottom, eyelid_l_bottom[2], eyelid_l_bottom[5], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_bottom, eyelid_l_bottom[0], eyelid_l_bottom[4], color=(255, 0, 0), thickness=1)
cv2.line(image_resize_bottom, eyelid_l_bottom[1], eyelid_l_bottom[3], color=(255, 0, 0), thickness=1)
plt.imshow(points_eyelid_bottom[...,::-1]) 
plt.show()
# open new window

In [119]:
eyelid_l_bottom[0]

array([188, 263])

In [120]:
print(distance_entre_points(eyelid_l_bottom, 2, 5))

7.211102550927978


In [121]:
print(distance_entre_points(eyelid_l_mid, 2, 5))

6.708203932499369


In [122]:
print(distance_entre_points(eyelid_l_top, 2, 5))

6.4031242374328485


In [123]:
print(distance_entre_points(eyelid_l_bottom, 0, 4))

7.280109889280518


In [124]:
print(distance_entre_points(eyelid_l_mid, 0, 4))

6.324555320336759


In [125]:
print(distance_entre_points(eyelid_l_top, 0, 4))

6.324555320336759


In [126]:
print(distance_entre_points(eyelid_l_bottom, 1, 3))

6.0


In [127]:
print(distance_entre_points(eyelid_l_mid, 1, 3))

5.0


In [128]:
print(distance_entre_points(eyelid_l_top, 1, 3))

4.0


In [129]:
pairs_l = [(2, 5), (0, 4), (1, 3)]
print(distance_mean(eyelid_l_bottom, pairs_l))
print(distance_mean(eyelid_l_mid, pairs_l))
print(distance_mean(eyelid_l_top, pairs_l))

6.830404146736165
6.0109197509453764
5.575893185923203


In [130]:
print(eyelid_comparsion(eyelid_l_bottom, eyelid_l_mid, eyelid_l_top, pairs_l))

Os olhos se abaixaram, comportamento esperado
