In [1]:
from src.mediapipe import GooMedia
import cv2
import numpy as np
from src.visualize import *
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from src.utils import image_resize
from src.geometry import *
from PIL import Image
import mediapipe as mp

In [2]:
%matplotlib qt

In [3]:
pface = GooMedia(1080) # Extrator dos pontos

In [4]:
image = cv2.imread(r"images\inputs\36pointscamera\36points_x42_y42.jpg")

In [5]:
# Resize image
image_r = cv2.resize(image, (480, 640)) 

In [6]:
image_resize , landmask = pface.extract(image_r)

c:\Users\artur\.conda\envs\space_human\lib\site-packages\google\protobuf\symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '


In [7]:
points = pface.points_normalize(landmask, image_r.shape)


In [8]:
print(points)

[(249, 372), (246, 338), (247, 347), (238, 301), (246, 326), (246, 311), (245, 275), (181, 275), (245, 251), (244, 238), (243, 182), (249, 375), (249, 379), (249, 381), (249, 381), (249, 385), (249, 389), (249, 395), (249, 405), (247, 343), (237, 342), (145, 234), (209, 283), (199, 284), (190, 284), (178, 279), (218, 279), (189, 255), (201, 255), (179, 257), (173, 262), (172, 285), (216, 424), (178, 272), (144, 280), (162, 277), (201, 327), (238, 370), (240, 379), (228, 373), (222, 377), (232, 380), (226, 381), (209, 391), (238, 337), (237, 327), (159, 253), (219, 299), (217, 333), (217, 327), (174, 326), (237, 313), (175, 243), (164, 246), (152, 215), (220, 248), (212, 258), (201, 382), (159, 378), (224, 339), (232, 342), (215, 384), (217, 384), (159, 240), (217, 338), (193, 242), (190, 234), (188, 189), (159, 226), (194, 210), (154, 248), (151, 241), (239, 375), (230, 377), (224, 379), (226, 341), (216, 384), (220, 385), (218, 384), (228, 337), (227, 382), (233, 381), (241, 381), (23

In [9]:
get_points_media(points, 'nose')

array([[246, 338],
       [238, 301],
       [246, 326],
       [246, 311],
       [245, 275],
       [247, 343],
       [237, 342],
       [238, 337],
       [237, 327],
       [237, 313],
       [228, 337],
       [247, 345],
       [225, 292],
       [222, 330],
       [237, 278],
       [242, 342],
       [222, 323],
       [229, 316],
       [243, 344],
       [231, 284],
       [246, 299],
       [225, 313],
       [226, 303],
       [225, 335],
       [229, 328],
       [144, 303],
       [231, 306],
       [232, 336],
       [237, 341],
       [232, 337],
       [223, 342],
       [239, 342],
       [240, 344],
       [254, 300],
       [256, 341],
       [254, 337],
       [255, 326],
       [254, 312],
       [266, 335],
       [267, 291],
       [271, 328],
       [255, 278],
       [335, 259],
       [252, 342],
       [271, 321],
       [263, 315],
       [251, 344],
       [261, 294],
       [261, 283],
       [268, 311],
       [267, 301],
       [268, 333],
       [264,

In [10]:
nose = get_points_media(points, 'nose')

In [11]:
len(nose)

61

In [12]:
points_face = draw_face_one_color(image_resize, nose)

In [13]:
plt.figure()
plt.imshow(points_face[...,::-1]) 
plt.show()
# open new window

In [204]:
points_pos = np.arange(1, len(points)+1)

In [205]:
points_pos

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [206]:
type(points_pos)

numpy.ndarray

In [207]:
np.array(points)

array([[249, 372],
       [246, 338],
       [247, 347],
       [238, 301],
       [246, 326],
       [246, 311],
       [245, 275],
       [181, 275],
       [245, 251],
       [244, 238],
       [243, 182],
       [249, 375],
       [249, 379],
       [249, 381],
       [249, 381],
       [249, 385],
       [249, 389],
       [249, 395],
       [249, 405],
       [247, 343],
       [237, 342],
       [145, 234],
       [209, 283],
       [199, 284],
       [190, 284],
       [178, 279],
       [218, 279],
       [189, 255],
       [201, 255],
       [179, 257],
       [173, 262],
       [172, 285],
       [216, 424],
       [178, 272],
       [144, 280],
       [162, 277],
       [201, 327],
       [238, 370],
       [240, 379],
       [228, 373],
       [222, 377],
       [232, 380],
       [226, 381],
       [209, 391],
       [238, 337],
       [237, 327],
       [159, 253],
       [219, 299],
       [217, 333],
       [217, 327],
       [174, 326],
       [237, 313],
       [175,

In [208]:
len(points)

478

In [209]:
dicionario = {i+1: coordenada for i, coordenada in enumerate(points)}

In [210]:
dicionario

{1: (249, 372),
 2: (246, 338),
 3: (247, 347),
 4: (238, 301),
 5: (246, 326),
 6: (246, 311),
 7: (245, 275),
 8: (181, 275),
 9: (245, 251),
 10: (244, 238),
 11: (243, 182),
 12: (249, 375),
 13: (249, 379),
 14: (249, 381),
 15: (249, 381),
 16: (249, 385),
 17: (249, 389),
 18: (249, 395),
 19: (249, 405),
 20: (247, 343),
 21: (237, 342),
 22: (145, 234),
 23: (209, 283),
 24: (199, 284),
 25: (190, 284),
 26: (178, 279),
 27: (218, 279),
 28: (189, 255),
 29: (201, 255),
 30: (179, 257),
 31: (173, 262),
 32: (172, 285),
 33: (216, 424),
 34: (178, 272),
 35: (144, 280),
 36: (162, 277),
 37: (201, 327),
 38: (238, 370),
 39: (240, 379),
 40: (228, 373),
 41: (222, 377),
 42: (232, 380),
 43: (226, 381),
 44: (209, 391),
 45: (238, 337),
 46: (237, 327),
 47: (159, 253),
 48: (219, 299),
 49: (217, 333),
 50: (217, 327),
 51: (174, 326),
 52: (237, 313),
 53: (175, 243),
 54: (164, 246),
 55: (152, 215),
 56: (220, 248),
 57: (212, 258),
 58: (201, 382),
 59: (159, 378),
 60: (

In [211]:
LEFT_EYE = [362, 382, 381, 380, 374, 373, 390, 249, 263, 466, 388, 387, 386, 385, 384, 398]
RIGHT_EYE = [33, 7, 163, 144, 145, 153, 154, 155, 133, 173, 157, 158, 159, 160, 161, 246]
LEFT_IRIS = [474, 475, 476, 477]
RIGHT_IRIS = [469, 470, 471, 472]
EYE_CENTER_LEFT = [468]
EYE_CENTER_RIGHT = [473]

In [212]:
# Mudança de base
#LEFT_EYE = [x + 1 for x in LEFT_EYE]
#RIGHT_EYE = [x + 1 for x in RIGHT_EYE]
#LEFT_IRIS = [x + 1 for x in LEFT_IRIS]
#RIGHT_IRIS = [x + 1 for x in RIGHT_IRIS]

In [213]:
# Defina as listas de índices dos olhos e íris
eyes_and_irises = [LEFT_EYE, RIGHT_EYE, LEFT_IRIS, RIGHT_IRIS, EYE_CENTER_LEFT, EYE_CENTER_RIGHT]

# Crie um dicionário vazio para armazenar os resultados
result = {}

# Loop pelas listas de índices
for eye_or_iris in eyes_and_irises:
    # Loop pelos índices da lista atual
    for index in eye_or_iris:
        # Verifique se o índice está no dicionário
        if index in dicionario:
            # Adicione o valor do dicionário ao resultado
            result[index] = dicionario[index]

# Imprima os resultados
print(result)

{363: (275, 271), 383: (278, 272), 382: (283, 273), 381: (290, 274), 375: (298, 275), 374: (306, 275), 391: (312, 273), 250: (315, 270), 264: (319, 267), 467: (317, 266), 389: (314, 264), 388: (309, 261), 387: (301, 260), 386: (292, 260), 385: (284, 263), 399: (278, 268), 34: (178, 272), 8: (181, 275), 164: (184, 277), 145: (190, 279), 146: (198, 279), 154: (207, 277), 155: (215, 275), 156: (220, 273), 134: (223, 272), 174: (220, 269), 158: (213, 265), 159: (203, 263), 160: (194, 264), 161: (185, 266), 162: (181, 269), 247: (179, 271), 475: (307, 266), 476: (297, 257), 477: (287, 266), 478: (298, 275), 470: (208, 268), 471: (197, 260), 472: (187, 270), 473: (199, 278), 468: (323, 261)}


In [214]:
type(eyes_and_irises)

list

In [215]:
ALL_INDICES = set(LEFT_EYE +  RIGHT_EYE + LEFT_IRIS + RIGHT_IRIS + EYE_CENTER_LEFT + EYE_CENTER_RIGHT)

In [216]:
type(ALL_INDICES)

set

In [217]:
def filter_points(all_points, indices):
    return [all_points[i] for i in indices if i < len(all_points)]

In [218]:
# Filter points based on the specified indices
points = filter_points(points, ALL_INDICES)

In [219]:
len(points)

40

In [220]:
# Create a copy of the frame for drawing
display_frame = image_resize.copy()

# Draw face points
for point in points:
    cv2.circle(display_frame, tuple(point), 2, (0, 255, 0), -1)

In [221]:
landmask_image = np.zeros_like(display_frame)
for point in points:
    cv2.circle(landmask_image, tuple(point), 2, (255, 255, 255), -1)
    landmask_image = 255 - landmask_image


In [222]:
cv2.imshow('Face Analysis', display_frame)
cv2.imshow('Landmask', landmask_image)         

In [223]:
plt.figure()
plt.imshow(landmask_image)
plt.figure()
plt.imshow(display_frame[...,::-1])
plt.show()

In [31]:
import json

# Converta o dicionário para um JSON
json_result = json.dumps(result)

# Salve o JSON em um arquivo
with open('result.json', 'w') as f:
    f.write(json_result)